core/models/schedules.go

Should be deployed after https://github.com/nyaruka/rapidpro/pull/4255

Stop reading from `msgs_broadcast.text`

---

core/handlers/msg_created_test.go
core/models/msgs.go
core/models/msgs_test.go

Need to ship https://github.com/nyaruka/courier/pull/559 and https://github.com/nyaruka/courier/pull/560 first

Stop adding language and country to msg.metadata.templating

---

core/handlers/msg_created_test.go
core/models/msgs.go
core/models/msgs_test.go

and fix not writing them to the db

Stop writing quick replies to metadata 

---

core/models/broadcasts.go
core/models/broadcasts_test.go
core/search/resolve.go
core/search/resolve_test.go
core/tasks/msgs/send_broadcast_test.go
core/tasks/starts/worker.go
go.mod
services/tickets/utils.go
testsuite/testdata/contacts.go

To make it easier to share code with resolving recipients for broadcasts.

Refactor how we resolve recipients for flow starts

---

core/models/msgs.go
core/models/starts.go
core/tasks/ivr/cron_test.go
core/tasks/ivr/start_ivr_flow_batch_test.go
core/tasks/msgs/send_broadcast.go
core/tasks/msgs/send_broadcast_batch.go
core/tasks/starts/start_flow.go
web/ivr/ivr_test.go

by consolidating broadcast and flow start task code

Support contact query based broadcasts

---

core/handlers/msg_received.go
core/models/msgs.go
core/models/msgs_test.go
core/runner/runner_test.go

See https://github.com/nyaruka/rapidpro/pull/4326

Use `msg_type = T|V` for outgoing messages

---

core/msgio/courier.go
core/msgio/courier_test.go

See https://github.com/nyaruka/courier/pull/581

Remove fields from courier payload that it doesn't use

---

core/msgio/courier.go

Users love to start a flow, panic, and then delete it

Still queue a courier message even if fetching the flow fails

---

core/search/search.go
core/search/search_test.go
web/flow/preview_start.go
web/flow/testdata/preview_start.json
web/msg/preview_broadcast.go
web/msg/testdata/preview_broadcast.json

which now only need to return total count
Requires https://github.com/nyaruka/rapidpro/pull/4613

Stop returning sample contacts on preview endpoints

---

core/ivr/ivr.go
core/models/channel_logs.go
web/contact/search.go
web/ivr/ivr.go
web/ivr/ivr_test.go

Requires https://github.com/nyaruka/rapidpro/pull/4631

Stop writing `ChannelLog.call`

---

core/models/sessions.go
mailroom.go
runtime/config.go

Rename sessions bucket config setting for clarity and remove unused sessions prefix setting

Config tweaks

---

core/models/contacts.go
core/models/contacts_test.go
core/models/msgs_test.go
core/models/testdata/imports.json
web/contact/testdata/bulk_create.json
web/contact/testdata/create.json
web/contact/testdata/modify.json
web/contact/testdata/resolve.json
web/ivr/ivr_test.go
web/msg/testdata/send.json

Don't encode priority in URN strings

---

core/models/channel_event.go
core/models/triggers.go
core/models/triggers_test.go
core/tasks/handler/contact_tasks.go
core/tasks/handler/handle_contact_event.go
core/tasks/handler/handle_contact_event_test.go
testsuite/testdata/triggers.go
testsuite/testsuite.go

Goes with https://github.com/nyaruka/courier/pull/639

Add support for optin/optout triggers and channel events

---

core/handlers/noop.go
core/msgio/courier.go
core/msgio/courier_test.go

and queue messages to courier with type

Add temp NOOP handler for `optin_created` events

---

core/tasks/analytics/cron.go
core/tasks/campaigns/cron.go
core/tasks/campaigns/fire_campaign_event.go
core/tasks/contacts/populate_dynamic_group.go
core/tasks/expirations/cron.go
core/tasks/handler/contact_tasks.go
core/tasks/handler/cron.go
core/tasks/handler/handle_contact_event.go
core/tasks/incidents/end_incidents.go
core/tasks/ivr/cron.go
core/tasks/ivr/start_ivr_flow_batch.go
core/tasks/msgs/retry_errored_messages.go
core/tasks/msgs/send_broadcast.go
core/tasks/msgs/send_broadcast_batch.go
core/tasks/schedules/cron.go
core/tasks/starts/start_flow.go
core/tasks/timeouts/cron.go

Replace more logrus use by slog in tasks

---

core/models/templates.go
core/models/templates_test.go
core/msgio/courier_test.go
go.mod
go.sum

Start loading template translation params

Template components

---

core/queue/lua/size.lua
core/queue/queue.go
core/queue/queue_test.go

It's currently not liable to race conditions.. things can be added and removed whilst it's adding up individual queue sizes

Move `queue.Size` functionality into lua script

---

core/models/groups.go
core/models/groups_test.go

https://textit.sentry.io/issues/5073062508

Fix getting group count for export preview

---

core/handlers/ivr_created.go
core/handlers/msg_created.go
core/handlers/optin_requested.go
core/ivr/ivr.go
core/models/msgs.go
core/models/msgs_test.go
core/msgio/courier_test.go
web/msg/testdata/send.json

...because for contact history ordering we need it be event time

Revert changes to make Msg.created_on be db time 

---

web/android/base_test.go
web/android/event.go
web/android/message.go
web/android/testdata/event.json
web/android/testdata/message.json

So we can migrate RP to call these with phone numbers and then do URN stuff in mailroom instead of RP.

Support either urn or phone on android endpoints

---

web/android/base.go
web/android/base_test.go
web/android/event.go
web/android/message.go
web/android/testdata/event.json
web/android/testdata/message.json

Requires https://github.com/nyaruka/rapidpro/pull/5224

Remove support for urn field on android endpoints

---

core/search/groups.go
core/search/groups_test.go
core/search/search.go
core/search/search_test.go
core/tasks/contacts/populate_dynamic_group.go

https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html

Replace usage of deprecated elastic scroll API

---

core/models/broadcasts.go
core/models/runs.go
core/models/runs_test.go
core/models/sessions_test.go
core/tasks/expirations/cron_test.go
core/tasks/interrupts/interrupt_channel_test.go
core/tasks/interrupts/interrupt_sessions_test.go
core/tasks/starts/start_flow_test.go
testsuite/testdata/flows.go
web/errors.go
web/msg/base_test.go
web/msg/broadcast.go
web/msg/testdata/broadcast.json

This endpoint isn't currently used.. but it will be!

Add node UUID param to msg/broadcast endpoint

---

core/models/broadcasts.go
core/models/campaigns.go
core/models/utils.go
core/models/utils_test.go

Fixes https://textit.sentry.io/issues/5529723052/?project=1285856

Fix creating broadcast to node with more than 65K contacts

---

core/models/channels.go
core/models/channels_test.go
core/msgio/android.go
core/msgio/android_test.go
core/msgio/send.go
core/msgio/send_test.go
core/tasks/channels/cron.go
core/tasks/channels/cron_test.go
testsuite/fcm.go
testsuite/testfiles/android.json
testsuite/testsuite.go

Add cron to trigger sync for old seen android channels

---

core/models/assets.go
core/models/broadcasts.go
core/models/broadcasts_test.go
core/models/msgs.go
core/models/msgs_test.go
core/models/templates.go
core/models/templates_test.go
core/msgio/courier.go
core/msgio/courier_test.go
testsuite/testdata/constants.go
web/msg/send.go

Add support for templates on broadcasts

---

core/models/templates.go

Stop reading from `TemplateTranslation.is_active`

---

web/errors.go
web/msg/broadcast.go
web/msg/testdata/broadcast.json

since this is no longer a thing we can resolve at request time

Remove special error case for broadcast with no recipients

---

utils/queues/fair_sorted.go
utils/queues/fair_sorted_test.go
utils/queues/lua/fair_sorted_pause.lua
utils/queues/lua/fair_sorted_pop.lua
utils/queues/lua/fair_sorted_resume.lua

Alternate implementation of #317 .. certainly simpler

Implement queue pausing and resuming by padding score

---

.github/workflows/ci.yml
core/models/contacts.go
core/models/contacts_test.go
core/models/sessions.go
core/models/utils.go
core/msgio/send.go
core/runner/runner.go
core/tasks/campaigns/cron.go
core/tasks/campaigns/fire_campaign_event.go
core/tasks/msgs/send_broadcast.go
core/tasks/starts/start_flow.go
go.mod
testsuite/testsuite.go
web/contact/modify.go
web/contact/urns.go
web/ticket/reopen.go

Uses a lot of `slices.Collect` which removes potential benefit of using iterators.. could improve upon that in future.

Update to go 1.23

---

core/tasks/task.go
mailroom.go

Requires https://github.com/nyaruka/courier/pull/785 and https://github.com/nyaruka/rapidpro/pull/5484

Remove old task queues

---

core/models/broadcasts.go

To match how we do it for starts

1/3 Add .broadcast field to broadcast batch tasks

---

core/hooks/create_broadcasts.go
core/hooks/create_starts.go
core/tasks/campaigns/cron.go
core/tasks/campaigns/fire_campaign_event_test.go
core/tasks/handler/handle_contact_event.go
core/tasks/handler/queue.go
core/tasks/interrupts/interrupt_channel_test.go
core/tasks/ivr/cron_test.go
core/tasks/ivr/start_ivr_flow_batch_test.go
core/tasks/msgs/send_broadcast.go
core/tasks/msgs/send_broadcast_test.go
core/tasks/schedules/cron.go
core/tasks/starts/start_flow.go
core/tasks/starts/start_flow_batch_test.go
core/tasks/starts/start_flow_test.go
core/tasks/starts/throttle_queue.go
core/tasks/starts/throttle_queue_test.go
core/tasks/task.go
testsuite/tasks.go
utils/queues/base.go
utils/queues/fair_sorted.go
utils/queues/fair_sorted_test.go
web/ivr/ivr_test.go
web/msg/broadcast.go
workers.go
workers_test.go

so it would be possible to switch out the sorted set implementation

Create abstraction for fair queues

---

core/tasks/expirations/bulk_expire.go
core/tasks/expirations/bulk_expire_test.go
core/tasks/expirations/cron.go
core/tasks/expirations/cron_test.go
core/tasks/timeouts/cron.go
core/tasks/timeouts/cron_test.go

Second half of https://github.com/nyaruka/mailroom/issues/356

Add task to handle throttled expirations

---

core/models/campaigns.go
core/models/contacts.go
core/models/sessions.go
core/tasks/campaigns/bulk_campaign_trigger.go
core/tasks/campaigns/bulk_campaign_trigger_test.go
core/tasks/campaigns/fire_campaign_event.go
core/tasks/contacts/cron.go
core/tasks/contacts/cron_test.go
testsuite/assert.go
testsuite/testdata/contacts.go

Part 1 of https://github.com/nyaruka/mailroom/issues/440

Implement triggering of campaign events from new contact fires model

---

core/handlers/campaigns_test.go
core/hooks/update_campaign_events.go
core/models/campaigns.go
core/models/campaigns_test.go
core/models/contact_fire.go
core/models/contacts.go
core/search/groups_test.go
core/tasks/campaigns/schedule_campaign_event_test.go
core/tasks/handler/ctasks/event_received_test.go
web/contact/testdata/modify.json

* anytime we delete fires we delete from `campaign_eventfire` as well as `contacts_contactfire`
* anytime we insert fires we only insert in `contacts_contactfire`

Start inserting new fires for campaign events

---

core/ivr/ivr.go
core/models/sessions.go
core/tasks/handler/ctasks/wait_expired.go

So there's just one task for messaging and voice flows

Add support to wait_expired ctask for voice sessions

---

core/models/campaigns.go
core/models/contact_fire.go

https://textit.sentry.io/issues/6339072198/

Ensure that campaign event fires are inserted in batches

---

core/tasks/handler/ctasks/event_received.go

Update incoming IVR call with session UUID

---

core/ivr/ivr.go
core/models/channel.go
core/tasks/starts/start_ivr_flow_batch_test.go

Requires https://github.com/nyaruka/rapidpro/pull/5988

Use channel config max_concurent_calls key

---

services/ivr/bandwidth/service.go
services/ivr/bandwidth/service_test.go

Renamed config key for BW voice application id
Requires migrations in https://github.com/nyaruka/rapidpro/pull/5999

Rename config for BW voice application ID

---

core/models/ticket.go
core/models/ticket_test.go
testsuite/testsuite.go
web/msg/testdata/send.json

Requires https://github.com/nyaruka/rapidpro/pull/6029

Stop writing old ticket daily counts and timings

---

core/ai/errors.go
services/llm/anthropic/service.go
services/llm/deepseek/service.go
services/llm/google/service.go
services/llm/openai/service.go
services/llm/openai_azure/service.go
web/errors.go
web/llm/testdata/translate.json
web/llm/translate.go

- Rebased this on the branch https://github.com/nyaruka/mailroom/pull/565/
- Add generic service error for LLM
- Contains https://github.com/nyaruka/mailroom/pull/563/

Adjust LLM service error

---

core/handlers/airtime_transferred.go
core/handlers/base_test.go
core/handlers/broadcast_created.go
core/handlers/contact_field_changed.go
core/handlers/contact_groups_changed.go
core/handlers/contact_language_changed.go
core/handlers/contact_name_changed.go
core/handlers/contact_status_changed.go
core/handlers/contact_urns_changed.go
core/handlers/email_sent.go
core/handlers/flow_entered.go
core/handlers/input_labels_added.go
core/handlers/ivr_created.go
core/handlers/llm_called.go
core/handlers/msg_created.go
core/handlers/msg_received.go
core/handlers/noop.go
core/handlers/optin_requested.go
core/handlers/resthook_called.go
core/handlers/session_triggered.go
core/handlers/sprint_ended.go
core/handlers/ticket_opened.go
core/handlers/warning.go
core/handlers/webhook_called.go
core/models/events.go
core/models/session.go

* Remove unused `tx` param from event handlers
* Convert `HandleSceneEvents` function into `Scene.AddEvents` method

Event handling cleanup

---

core/handlers/base_test.go
core/handlers/ivr_created.go
core/ivr/ivr.go
core/models/events.go
core/models/session.go
core/runner/resume.go
core/runner/resume_test.go
core/runner/start.go
core/tasks/handler/ctasks/event_received.go
core/tasks/handler/ctasks/msg_received.go
core/tasks/handler/ctasks/ticket_closed.go
core/tasks/handler/ctasks/wait_expired.go
core/tasks/handler/ctasks/wait_timeout.go

Scene creation also moves into runner bringing us closer to moving all of the event handling stuff there from models

Add call to Scene instead of using transient field on session and setting via hooks

---

core/models/assets.go
core/models/ticket.go
core/models/user_test.go
core/runner/handlers/ticket_opened.go
core/runner/handlers/ticket_opened_test.go
core/runner/start.go
go.mod
go.sum
web/contact/testdata/modify.json

Requires https://github.com/nyaruka/rapidpro/pull/6073

Update to latest goflow that changes user references to be by UUID

---

core/crons/retry_calls.go
core/crons/retry_errored_messages.go
core/models/contact.go
core/models/msg.go
core/models/msg_test.go
core/msgio/courier.go
core/msgio/courier_test.go
core/msgio/send.go
core/msgio/send_test.go
core/runner/hooks/send_messages.go
core/tasks/campaigns/bulk_campaign_trigger.go
core/tasks/msgs/send_broadcast_batch.go
testsuite/testdata/contacts.go
web/ivr/ivr.go
web/msg/handle.go
web/msg/resend.go
web/msg/send.go

* Move `Send` to models package so models functions can return sends
* Move `IsResend` and `LastInSprint` from `Msg` to `Send`
* Replace `URNForID` with `LoadContactURN`

More send improvments

---

core/models/msg.go
core/msgio/courier.go
core/msgio/courier_test.go
core/runner/events.go
core/runner/handlers/base_test.go
core/runner/handlers/sprint_ended.go
core/runner/hooks/send_messages.go
core/runner/resume.go
core/runner/start.go

* Add Sprint to Scene and SprintUUID to Send

Scenes without model sessions part 1

---

core/ivr/ivr.go
core/models/channel.go
core/models/contact_fire_test.go
core/models/msg.go
core/models/session.go
core/models/session_test.go
core/runner/events.go
core/runner/handlers/base_test.go
core/runner/handlers/msg_received.go
core/runner/hooks/update_campaign_events.go
core/runner/hooks/update_contact_modified_on.go
core/runner/hooks/update_message_handled.go
core/runner/modifiers.go
core/runner/resume.go
core/runner/resume_test.go
core/runner/start.go
core/runner/start_test.go
core/tasks/handler/ctasks/event_received.go
core/tasks/handler/ctasks/msg_received.go
core/tasks/handler/ctasks/ticket_closed.go
core/tasks/handler/ctasks/wait_expired.go
core/tasks/handler/ctasks/wait_timeout.go

`msg_received` event -> `update_message_handled` hook

Mark messages handled via event and hook

---

core/ivr/ivr.go
core/models/contact_fire_test.go
core/models/session.go
core/models/session_test.go
core/runner/handlers/base_test.go
core/runner/resume_test.go
core/runner/start.go
core/runner/start_test.go
core/tasks/campaigns/bulk_campaign_trigger.go
core/tasks/handler/ctasks/event_received.go
core/tasks/handler/ctasks/msg_received.go
core/tasks/handler/ctasks/ticket_closed.go

To bring us closer to batching starts that aren't necessarily the same flow etc

Rework runner.StartFlow

---

core/ivr/ivr.go
core/runner/handlers/sprint_ended_test.go
core/runner/resume.go
core/runner/resume_test.go
core/tasks/handler/ctasks/msg_received.go
core/tasks/handler/ctasks/wait_expired.go
core/tasks/handler/ctasks/wait_timeout.go
web/ivr/ivr.go

and rename some IVR functions for clarity

Pass call to runner.Resume via scene
