nyaruka/mailroom

core/models/campaigns.go

We have a GIN index on contact fields 
```sql
CREATE INDEX contact_fields_keys_idx ON public.contacts_contact USING gin (extract_jsonb_keys(fields))
```
Which was supposed to be for this but it's not being used, and it doesn't feel worth maintaining an index for this anyway, especially not a potentially expensive GIN one.

Tweak fetching contacts eligible for a new campaign event

---

services/ivr/vonage/client.go

Avoids..
```
{"type":400,"title":"Bad Request","invalid_parameters":[{"reason":"accepted values are continue and hangup","name":"machine_detection"}]}
```

Don't send `machine_detection` param to Nexmo if empty

---

core/models/broadcasts.go
core/models/msgs.go
core/models/starts.go
core/models/starts_test.go
core/search/resolve.go
core/search/resolve_test.go
core/tasks/msgs/send_broadcast.go
core/tasks/starts/start_flow.go

Mostly re-organizing code but contains one meaningful change - in the past for flow starts we've resolved URNs to contact ids and then saved those back onto the start for record keeping. I was going to make broadcasts do the same thing but have talked myself out of it because... in the case of starts, now pretty much everything is a query and we never save those contact ids back onto the start. So now I've gotten rid of that code for starts and given up on the idea that a start or broadcast should save the final set of contact ids. Even for groups it's misleading because contact membership can obviously change after a start or broadcast.

Cleanup broadcasts and starts

---

core/models/msgs.go
core/models/msgs_test.go

Fixes #42 
Currently we track repetitions using a hash table of `contact => text|count`, and this PR reworks it to `contact|text => count`

Improve detection of repeated outgoing messages

---

core/hooks/send_messages.go
core/models/msgs.go
core/msgio/courier.go
core/msgio/courier_test.go
web/msg/base_test.go

* Fix not queuing chat/ticket messages as high priority
* Add `contact_last_seen_on` to queued messages
* Simplify transient fields on `models.Msg` which are only needed for courier

🚦 Courier queuing updates

---

core/models/contacts.go
core/models/contacts_test.go
core/runner/runner.go
core/tasks/handler/handle_contact_event.go

Because I want to make it easier to add locking elsewhere.. where we modify contacts.
If we lock on the modify endpoint, that should be enough to prevent ever opening more than one ticket for a contact, even without a db level contraint.
And it should also prevent a certain class of deadlock that we occasionally see.

🔐 Refactor how we lock and unlock contacts

---

core/msgio/android.go
core/msgio/android_test.go

Apparently this is quite normal..

Just noop if trying to sync an Android channel that doesn't have an FCM ID

---

core/models/channel_event.go
core/models/channel_event_test.go
core/tasks/handler/contact_tasks.go
core/tasks/handler/handle_contact_event_test.go

Courier channel events extra are always string -> string... I forgot about android syncs from RP (e.g. https://textit.sentry.io/issues/4472957645/)

Fix not supporting channel events with extra with non-string values

---

core/handlers/base_test.go
core/models/contacts.go
core/tasks/handler/contact_tasks.go
testsuite/testdata/contacts.go
web/ivr/ivr.go
web/msg/testdata/send.json

And ignore events rather than error when contact no longer exists
Fixes panics where we try to handle a task but the contact has been deleted. e.g. https://textit.sentry.io/issues/4506966895/

Simplify where we load a single contact 

---

core/hooks/insert_start.go
core/models/schedules_test.go
core/models/starts.go
core/models/starts_test.go
core/runner/runner_test.go
core/tasks/handler/contact_tasks.go
core/tasks/ivr/cron_test.go
core/tasks/ivr/start_ivr_flow_batch_test.go
core/tasks/starts/start_flow.go
core/tasks/starts/start_flow_test.go
web/ivr/ivr_test.go

It's redundant since we load the flow anyway when creating batches

Don't require `flow_type` on queued flow start tasks

---

core/models/schedules.go
core/tasks/schedules/cron_test.go

Not convinced there's value in keeping them around indefinitely and I want to get to a point where `Schedule.next_fire` is non-null

Actually delete schedule objects instead of soft deletes

---

core/handlers/ivr_created.go
core/handlers/msg_created.go
core/handlers/optin_requested.go
core/ivr/ivr.go
core/models/broadcasts.go
core/models/msgs.go
core/models/msgs_test.go
core/msgio/courier_test.go
core/runner/runner_test.go
web/msg/send.go
web/msg/testdata/send.json

* Make `Msg.created_on` always be db insertion time
* Stop writing `queued_on` which isn't meaningful - it was being set to db insert time because we create outgoing messages with status=Q to save having to update them after queuing.

Simplify message time fields

---

core/models/broadcasts.go
core/models/broadcasts_test.go
core/models/schedules.go
core/models/schedules_test.go
core/tasks/msgs/send_broadcast_test.go
web/msg/broadcast.go

`TemplateState` getting a bit confusing alongside `TemplateID` and `TemplateVariables` that mean something completely different. Matches https://github.com/nyaruka/rapidpro/pull/5350

Deprecate `broadcast.template_state` and add `broadcast.expressions`

---

core/hooks/send_messages.go
core/msgio/android.go
core/msgio/android_test.go
core/msgio/send.go
core/msgio/send_test.go
core/tasks/channels/cron.go
core/tasks/channels/cron_test.go
core/tasks/msgs/retry_errored_messages.go
core/tasks/msgs/send_broadcast_batch.go
go.mod
mailroom.go
runtime/runtime.go
testsuite/fcm.go
testsuite/testsuite.go
web/android/sync.go
web/msg/resend.go
web/msg/send.go

* Move client onto runtime
* Simplify testing - tokens and messages are properties of the mocked client, no more "service"

Refactor FCM functionality

---

core/tasks/task.go
mailroom.go

Gonna switch over the others as well so then our main queues will be named like `tasks:` (mailroom) and `msgs:` (courier)

Rename throttled redis queue to tasks:throttled

---

web/contact/base_test.go
web/contact/deindex.go
web/contact/testdata/deindex.json

Want mailroom to take over indexing of contacts... but mailroom generally only knows about active contacts.
So thinking of a two step process where first step is that mailroom takes over de-indexing deleted contacts, rp-indexer starts ignoring deleted contacts.

Add endpoint to de-index specific contacts

---

web/contact/base_test.go
web/contact/deindex.go
web/contact/testdata/deindex.json

so that it can be run before deletion actually occurs

Remove check in deindex contact for contact being inactive

---

core/models/assets.go
core/models/contacts.go
core/models/contacts_test.go
core/models/fields_test.go
core/models/groups.go
core/models/groups_test.go
core/search/search.go

See https://github.com/nyaruka/rapidpro/issues/5529
And converts searches based on status groups to use a status condition instead.

Don't include db-trigger maintained status groups in engine assets

---

core/tasks/timeouts/bulk_timeout.go
core/tasks/timeouts/bulk_timeout_test.go
core/tasks/timeouts/cron.go
core/tasks/timeouts/cron_test.go

Addresses half of https://github.com/nyaruka/mailroom/issues/356.
If an org has < 10 timeouts then they are queued directly to the handler queue as we've always done.
If an org has >= 10 timeouts then they are queued as bulk timeout tasks (batches of 100) in the throttle queue (the one throttled by outbox size).

Add new task to handle bulk session timeouts

---

web/ticket/base.go
web/ticket/close.go

which was only used for external ticketing services

Remove force option from ticket close endpoint

---

core/tasks/contacts/bulk_session_expire.go
core/tasks/contacts/bulk_session_expire_test.go
core/tasks/contacts/bulk_session_timeout.go
core/tasks/contacts/bulk_session_timeout_test.go
core/tasks/expirations/bulk_expire.go
core/tasks/expirations/cron.go
core/tasks/expirations/cron_test.go
core/tasks/timeouts/bulk_timeout.go
core/tasks/timeouts/cron.go
core/tasks/timeouts/cron_test.go

The existing ones use data structures from the cron tasks.. which we want to replace.

Add new tasks for bulk session expires and timeouts

---

core/models/contact_fire.go
core/tasks/expirations/cron.go
core/tasks/expirations/cron_test.go
core/tasks/ivr/bulk_call_hangup.go
core/tasks/ivr/bulk_call_hangup_test.go

Requires index changes in https://github.com/nyaruka/rapidpro/pull/5824

Merge crons for expiring message and voice sessions

---

core/tasks/contacts/bulk_wait_expire.go
core/tasks/contacts/bulk_wait_expire_test.go
core/tasks/contacts/bulk_wait_timeout.go
core/tasks/contacts/bulk_wait_timeout_test.go
core/tasks/contacts/cron.go
core/tasks/contacts/cron_test.go

Because `bulk_session_expire` would be the name of a task that handles the overall expiry of a session.. not just a wait within it.. and I think we're going to add that.

Tweak task names used for wait expirations and timeouts

---

runtime/config.go

Reduce webhook service fetch limit to 256KiB

---

web/campaign/base_test.go
web/campaign/schedule_event.go
web/campaign/testdata/schedule_event.json
web/msg/base_test.go
web/msg/broadcast.go

One day it would be nice if RP knows nothing about mailroom task queuing

Add endpoint to schedule fires for a new campaign event

---

core/models/org.go
core/models/org_test.go
go.mod
web/org/metrics.go

This fixes trying to get metrics for org with `is_active = FALSE` to properly return invalid authentication
https://textit.sentry.io/issues/6374553449

Only allow getting org id for active orgs and Replace deprecated dependency

---

core/handlers/contact_field_changed.go
core/handlers/contact_groups_changed.go
core/handlers/contact_language_changed.go
core/handlers/contact_name_changed.go
core/handlers/contact_status_changed.go
core/handlers/contact_urns_changed.go
core/handlers/sprint_ended.go
core/hooks/commit_added_labels.go
core/hooks/commit_field_changes.go
core/hooks/commit_group_changes.go
core/hooks/commit_ivr.go
core/hooks/commit_language_changes.go
core/hooks/commit_messages.go
core/hooks/commit_name_changes.go
core/hooks/commit_session_changes.go
core/hooks/commit_status_changes.go
core/hooks/commit_urn_changes.go
core/hooks/contact_last_seen.go
core/hooks/contact_modified.go
core/hooks/create_broadcasts.go
core/hooks/create_starts.go
core/hooks/insert_airtime_transfers.go
core/hooks/insert_http_logs.go
core/hooks/insert_tickets.go
core/hooks/insert_webhook_event.go
core/hooks/monitor_webhooks.go
core/hooks/send_messages.go
core/hooks/unsubscribe_resthook.go
core/hooks/update_campaign_events.go
core/models/events.go

* Add ordering to scene hooks
* Always attach contact modified on hook as pre-commit hook, ordered last
Goal is post-commit hooks only being for things like message queuing and not making database changes

Ordered scene hooks
